import { area, checks, date, form, odos, section, select, text, yesno } from "../fields";
import type { PracticeForm } from "../types";
import {
  COMMON_DIAGNOSES,
  EXAM_WNL,
  anteriorSection,
  assessmentPlanSection,
  entranceSection,
  historyStrip,
  hpiSection,
  iopSection,
  posteriorSection,
  refractionSection,
  testingSection,
  visitHeader,
} from "./exam-shared";

const comprehensiveSections = [
  visitHeader(),
  hpiSection(),
  historyStrip(),
  entranceSection(),
  refractionSection(),
  iopSection(),
  anteriorSection(),
  posteriorSection(),
  testingSection(),
  assessmentPlanSection(COMMON_DIAGNOSES),
];

export const examForms: PracticeForm[] = [
  form({
    slug: "comprehensive-exam",
    title: "Comprehensive Adult Eye Examination",
    shortTitle: "Comprehensive exam",
    category: "exam",
    audience: "clinician",
    description:
      "Full 92004/92014 template: HPI, entrance tests, refraction, IOP, slit lamp, DFE, testing, spectacle/CL Rx, assessment and plan.",
    ottehrSlot: "global-template",
    cptHints: ["92004", "92014", "92015"],
    wnlDefaults: EXAM_WNL,
    sections: comprehensiveSections,
  }),

  form({
    slug: "intermediate-exam",
    title: "Intermediate Eye Examination",
    shortTitle: "Intermediate exam",
    category: "exam",
    audience: "clinician",
    description: "92002/92012 problem-oriented intermediate exam without a full refraction or DFE requirement.",
    ottehrSlot: "global-template",
    cptHints: ["92002", "92012"],
    wnlDefaults: EXAM_WNL,
    sections: [
      visitHeader(),
      hpiSection(),
      historyStrip(),
      entranceSection(),
      iopSection(),
      anteriorSection(),
      section("limited-posterior", "Posterior (undilated / limited)", [
        odos("undilated-view", "Direct / 90D undilated view"),
        area("posterior-notes", "Notes"),
      ]),
      assessmentPlanSection(COMMON_DIAGNOSES),
    ],
  }),

  form({
    slug: "problem-focused",
    title: "Problem-Focused Medical Visit (E/M)",
    shortTitle: "Medical E/M",
    category: "exam",
    audience: "clinician",
    description: "99213/99214 medical eye visit: MDM-forward, no routine refraction.",
    ottehrSlot: "global-template",
    cptHints: ["99213", "99214", "99203", "99204"],
    sections: [
      visitHeader([
        select("em-level", "Intended E/M", ["99212", "99213", "99214", "99202", "99203", "99204"]),
      ]),
      hpiSection(),
      historyStrip(),
      section("ros-pf", "Pertinent ROS", [
        checks("ros", "ROS", [
          "Constitutional",
          "Eyes",
          "ENT",
          "Cardiovascular",
          "Respiratory",
          "Neuro",
          "Endocrine",
          "Allergic",
        ]),
        area("ros-notes", "ROS notes"),
      ]),
      entranceSection(),
      iopSection(),
      anteriorSection(),
      posteriorSection(),
      testingSection(),
      assessmentPlanSection(COMMON_DIAGNOSES),
    ],
  }),

  form({
    slug: "contact-lens-new-fit",
    title: "Contact Lens New Fit",
    shortTitle: "CL new fit",
    category: "exam",
    audience: "clinician",
    description: "HVID, Ks, tear film, diagnostic lens, over-refraction, WTT, and dispense.",
    ottehrSlot: "global-template",
    cptHints: ["92310", "92311", "92072"],
    sections: [
      visitHeader(),
      hpiSection(),
      historyStrip(),
      entranceSection(),
      refractionSection(),
      anteriorSection(),
      section("cl-fit", "Diagnostic fitting", [
        odos("hvid", "HVID"),
        odos("pupil-size", "Pupil size photopic/scotopic"),
        select("modality", "Modality", [
          "Daily sphere",
          "Daily toric",
          "Daily MF",
          "Monthly sphere",
          "Monthly toric",
          "Monthly MF",
          "GP",
          "Scleral",
          "Hybrid",
          "Ortho-K",
        ]),
        odos("dx-lens", "Diagnostic lens (brand BC diam pwr)"),
        odos("fit-centration", "Centration / movement / lag"),
        odos("or", "Over-refraction"),
        odos("va-cl", "VA in diagnostic CL"),
        odos("wtt", "Wearing time today"),
        area("cl-plan", "Trial order / follow-up", true, 3),
      ]),
      assessmentPlanSection(["Myopia", "Hyperopia", "Astigmatism", "Presbyopia", "Contact lens fit", "Dry eye"]),
    ],
  }),

  form({
    slug: "contact-lens-followup",
    title: "Contact Lens Follow-up",
    shortTitle: "CL follow-up",
    category: "exam",
    audience: "clinician",
    description: "Overwear check, cornea, final Rx release decision.",
    ottehrSlot: "global-template",
    sections: [
      visitHeader(),
      section("fu", "Follow-up", [
        odos("wtt", "Average wear time"),
        yesno("sleep-in-lenses", "Sleeping in lenses?"),
        area("symptoms", "Comfort / vision complaints", false, 2),
        odos("va-cl", "VA in habitual CL"),
        odos("or", "Over-refraction"),
      ]),
      anteriorSection(),
      section("decision", "Rx decision", [
        select("status", "Status", ["Final Rx — release", "Continue trial", "Change parameters", "Discontinue CL"], true),
        area("final-params", "Final parameters"),
        ...assessmentPlanSection(["Contact lens follow-up", "Corneal staining", "GPC", "Overwear"]).fields,
      ]),
    ],
  }),

  form({
    slug: "pediatric-exam",
    title: "Pediatric Eye Examination",
    shortTitle: "Pediatric exam",
    category: "exam",
    audience: "clinician",
    description: "Age-appropriate VA, alignment, stereo, cycloplegic retinoscopy, and amblyopia risk.",
    ottehrSlot: "global-template",
    cptHints: ["92004", "92014", "99173"],
    sections: [
      visitHeader([text("age", "Age"), text("grade", "Grade")]),
      hpiSection(),
      section("dev", "Development / school", [
        yesno("premature", "Premature / NICU?"),
        yesno("iep", "IEP / reading difficulty?"),
        area("school-notes", "School / parent concerns"),
      ]),
      entranceSection(),
      section("align", "Binocular / pediatric extras", [
        odos("hirschberg", "Hirschberg / Bruckner"),
        odos("nct", "NCT / Krimsky"),
        odos("versions", "Versions / obliques"),
        odos("stereo-ped", "Stereo (Randot / Titmus)"),
        odos("ret", "Dry retinoscopy"),
        odos("cyclo-ret", "Cyclo retinoscopy"),
      ]),
      anteriorSection(),
      posteriorSection(),
      assessmentPlanSection([
        "Emmetropia",
        "Myopia",
        "Hyperopia",
        "Astigmatism",
        "Accommodative esotropia",
        "Amblyopia",
        "Convergence insufficiency",
        "Normal pediatric exam",
      ]),
    ],
  }),

  form({
    slug: "dry-eye-eval",
    title: "Dry Eye / OSD Evaluation",
    shortTitle: "Dry eye",
    category: "exam",
    audience: "clinician",
    description: "SPEED/OSDI, MGD, staining, osmolarity placeholders, stepwise therapy.",
    ottehrSlot: "global-template",
    icdHints: ["H04.123"],
    sections: [
      visitHeader(),
      hpiSection(),
      section("scores", "Questionnaires", [
        text("osdi", "OSDI score"),
        text("speed", "SPEED score"),
        yesno("screen-time-heavy", "High screen time?"),
        checks("meds-dry", "Dry-eye meds / exposures", [
          "Antihistamine",
          "Anticholinergic",
          "Isotretinoin",
          "CPAP",
          "Retinoid cream",
          "CL wear",
        ]),
      ]),
      entranceSection(),
      iopSection(),
      anteriorSection(),
      section("osd", "OSD metrics", [
        odos("tbut", "TBUT (sec)"),
        odos("staining", "NaFl / lissamine staining"),
        odos("mgd", "MG expression / dropout"),
        odos("lid-wiper", "Lid wiper"),
        odos("osmolarity", "Osmolarity"),
        odos("mmp9", "MMP-9"),
      ]),
      assessmentPlanSection([
        "Aqueous deficient dry eye",
        "Evaporative dry eye / MGD",
        "Mixed OSD",
        "Allergic component",
        "Exposure / lagophthalmos",
      ]),
    ],
  }),

  form({
    slug: "glaucoma-followup",
    title: "Glaucoma / Suspect Follow-up",
    shortTitle: "Glaucoma FU",
    category: "exam",
    audience: "clinician",
    description: "IOP, adherence, OCT RNFL, HVF, target pressure, drop plan.",
    ottehrSlot: "global-template",
    cptHints: ["92012", "99214", "92133", "92083"],
    icdHints: ["H40.013", "H40.11X3"],
    sections: [
      visitHeader(),
      section("glc-hpi", "Interval history", [
        area("interval", "Symptoms / drop intolerance / missed doses", true, 3),
        checks("drops", "Current drops", [
          "PG analog",
          "Beta blocker",
          "CAI",
          "Alpha agonist",
          "Rho kinase",
          "Combo",
          "None",
        ]),
        yesno("adherent", "Reports adherence?"),
      ]),
      entranceSection(),
      iopSection(),
      anteriorSection(),
      posteriorSection(),
      testingSection(),
      section("glc-mdm", "Glaucoma MDM", [
        odos("target-iop", "Target IOP"),
        select("stage", "Stage", ["Suspect", "Mild", "Moderate", "Severe", "Indeterminate"]),
        area("progression", "Progression analysis (OCT/HVF)"),
      ]),
      assessmentPlanSection(["Glaucoma suspect", "OHTN", "POAG", "NTG", "Narrow angle", "Secondary glaucoma"]),
    ],
  }),

  form({
    slug: "diabetic-exam",
    title: "Diabetic Eye Examination",
    shortTitle: "Diabetic exam",
    category: "exam",
    audience: "clinician",
    description: "Dilated diabetic retinopathy screening with ETDRS-style grading and PCP letter fields.",
    ottehrSlot: "global-template",
    cptHints: ["92014", "92250", "92134"],
    icdHints: ["E11.9", "E11.319", "E11.329", "E11.339", "E11.349", "E11.359"],
    sections: [
      visitHeader([
        text("pcp", "PCP / endocrinologist", true, { span: 2 }),
        text("diabetes-type", "Type", false, { placeholder: "T1 / T2" }),
        date("diabetes-onset", "Onset"),
        text("a1c", "Last A1c", true),
      ]),
      hpiSection(),
      historyStrip(),
      entranceSection(),
      iopSection(),
      anteriorSection(),
      posteriorSection(),
      section("dr", "Retinopathy grading", [
        odos("npdr-grade", "DR grade (none / mild / mod / severe NPDR / PDR)"),
        odos("dme", "DME"),
        odos("hemes", "H/Ma / CWS / VB / IRMA / NVE-NVD"),
        yesno("letter-pcp", "Send letter to PCP?"),
      ]),
      testingSection(),
      assessmentPlanSection([
        "No DR",
        "Mild NPDR",
        "Moderate NPDR",
        "Severe NPDR",
        "PDR",
        "DME",
        "Hypertensive retinopathy",
      ]),
    ],
  }),

  form({
    slug: "amd-followup",
    title: "Macular Degeneration Follow-up",
    shortTitle: "AMD FU",
    category: "exam",
    audience: "clinician",
    description: "Amsler, OCT macula, AREDS, conversion symptoms, retina referral trigger.",
    ottehrSlot: "global-template",
    cptHints: ["92134", "92250"],
    sections: [
      visitHeader(),
      section("amd-hpi", "Interval", [
        yesno("metamorphopsia", "New distortion?"),
        yesno("scotoma", "New spot / missing vision?"),
        odos("amsler", "Amsler"),
        checks("areds", "AREDS2 / smoking", ["On AREDS2", "Not on AREDS2", "Current smoker", "Former smoker"]),
      ]),
      entranceSection(),
      posteriorSection(),
      testingSection(),
      assessmentPlanSection(["Dry AMD — early", "Dry AMD — intermediate", "Geographic atrophy", "Wet AMD — refer"]),
    ],
  }),

  form({
    slug: "red-eye-urgent",
    title: "Red Eye / Urgent Visit",
    shortTitle: "Red eye",
    category: "exam",
    audience: "clinician",
    description: "Pain, photophobia, CL wear, dendritic vs bacterial vs uveitis workup.",
    ottehrSlot: "global-template",
    cptHints: ["99213", "99214", "92012"],
    sections: [
      visitHeader(),
      section("urgent-hpi", "Urgent HPI", [
        select("laterality", "Eye", ["OD", "OS", "OU"], true),
        yesno("cl-wearer", "Contact lens wearer?"),
        yesno("sleep-cl", "Slept in lenses?"),
        yesno("trauma", "Trauma / chemical / UV?"),
        yesno("photophobia", "Photophobia?"),
        yesno("discharge", "Discharge?"),
        area("hpi", "HPI", true, 3),
      ]),
      entranceSection(),
      iopSection(),
      anteriorSection(),
      section("seidel", "Cornea extras", [
        odos("seidel", "Seidel"),
        odos("ac-cells", "AC cell/flare"),
        odos("iop-compare", "IOP vs fellow eye"),
      ]),
      assessmentPlanSection([
        "Viral conjunctivitis",
        "Bacterial conjunctivitis",
        "Allergic conjunctivitis",
        "CL-related keratitis",
        "Corneal abrasion",
        "Anterior uveitis",
        "Episcleritis",
        "Angle closure — emergency",
      ]),
    ],
  }),

  form({
    slug: "cataract-preop",
    title: "Cataract Pre-operative Evaluation",
    shortTitle: "Cataract pre-op",
    category: "exam",
    audience: "clinician",
    description: "LOCS grading, lifestyle, IOL counseling, referral packet.",
    ottehrSlot: "global-template",
    sections: [
      visitHeader(),
      hpiSection(),
      entranceSection(),
      refractionSection(),
      iopSection(),
      anteriorSection(),
      posteriorSection(),
      section("cat", "Cataract counseling", [
        odos("locs", "LOCS / NS-CSC-PSC grade"),
        odos("glare-va", "Glare VA"),
        checks("iol-goals", "Goals", [
          "Distance glasses-free",
          "Readers OK",
          "Toric",
          "Presbyopia IOL discuss",
          "Monovision history",
        ]),
        text("surgeon", "Referred surgeon"),
        area("counseling", "Counseling documented"),
      ]),
      assessmentPlanSection(["NS cataract", "Cortical cataract", "PSC", "Visually significant cataract"]),
    ],
  }),

  form({
    slug: "cataract-postop",
    title: "Cataract Post-operative Visit",
    shortTitle: "Cataract post-op",
    category: "exam",
    audience: "clinician",
    description: "POD1 / POW1 / POM1 drops, Seidel, IOL position, CME watch.",
    ottehrSlot: "global-template",
    sections: [
      visitHeader([
        select("pod", "Visit", ["POD 1", "POW 1", "POW 2–3", "POM 1", "Later"], true),
        select("laterality", "Operated eye", ["OD", "OS"], true),
      ]),
      section("drops", "Drop adherence", [
        checks("drops", "Drops", ["Antibiotic", "Steroid", "NSAID", "IOP drop", "Other"]),
        area("symptoms", "Pain / flashes / floaters / vision"),
      ]),
      entranceSection(),
      iopSection(),
      anteriorSection(),
      posteriorSection(),
      assessmentPlanSection(["Normal post-op", "IOP spike", "Corneal edema", "Iritis", "PCO", "CME", "Refer back to surgeon"]),
    ],
  }),

  form({
    slug: "binocular-vision",
    title: "Binocular Vision / Vision Therapy Evaluation",
    shortTitle: "BV / VT eval",
    category: "exam",
    audience: "clinician",
    description: "Cover, phorias, vergences, accommodation, DEM/King-Devick placeholders.",
    ottehrSlot: "global-template",
    sections: [
      visitHeader(),
      hpiSection(),
      entranceSection(),
      section("bv", "BV workup", [
        odos("phoria-d", "Phoria distance"),
        odos("phoria-n", "Phoria near"),
        text("npc", "NPC (break/recovery)"),
        text("npa", "NPA / AA"),
        text("pfv", "PFV (blur/break/recov)"),
        text("nfv", "NFV"),
        text("nra-pra", "NRA / PRA"),
        text("bcc", "BCC / fused cross cyl"),
        odos("mem", "MEM"),
        text("dem", "DEM / King-Devick"),
      ]),
      assessmentPlanSection([
        "Convergence insufficiency",
        "Convergence excess",
        "Accommodative insufficiency",
        "Accommodative excess",
        "Saccadic dysfunction",
        "CI with VT plan",
      ]),
    ],
  }),

  form({
    slug: "low-vision",
    title: "Low Vision Evaluation",
    shortTitle: "Low vision",
    category: "exam",
    audience: "clinician",
    description: "Goals, ETDRS, contrast, devices, rehab referral.",
    ottehrSlot: "global-template",
    sections: [
      visitHeader(),
      section("goals", "Goals", [
        area("goals", "Patient goals (reading, TV, independent living, driving)", true, 3),
      ]),
      entranceSection(),
      section("lv", "Low-vision metrics", [
        odos("etdrs", "ETDRS / logMAR"),
        odos("contrast", "Contrast sensitivity"),
        odos("visual-field-lv", "Field / eccentric viewing"),
        area("devices", "Devices trialed (microscope, CCTV, filter, prism, software)"),
      ]),
      assessmentPlanSection(["Low vision — AMD", "Low vision — glaucoma", "Low vision — DR", "Low vision — other"]),
    ],
  }),

  form({
    slug: "sports-vision",
    title: "Sports / Occupational Vision",
    shortTitle: "Sports vision",
    category: "exam",
    audience: "clinician",
    description: "Reaction, peripheral awareness, protective eyewear, ANSI.",
    ottehrSlot: "global-template",
    sections: [
      visitHeader([text("sport", "Sport / occupation", true, { span: 2 })]),
      hpiSection(),
      entranceSection(),
      refractionSection(),
      section("sport", "Sports extras", [
        odos("dynamic-va", "Dynamic VA"),
        text("reaction", "Reaction / Brock string / saccades"),
        checks("protection", "Protection", ["ANSI Z87.1", "ASTM sport", "Polycarbonate mandated", "None currently"]),
        area("plan", "Plan", true),
      ]),
      assessmentPlanSection(["Needs protective eyewear", "CL for sport", "Performance VT", "Unrestricted"]),
    ],
  }),

  form({
    slug: "emergency-trauma",
    title: "Ocular Trauma / Emergency",
    shortTitle: "Trauma",
    category: "exam",
    audience: "clinician",
    description: "Mechanism, tetanus, Seidel, globe integrity, same-day retina/cornea referral.",
    ottehrSlot: "global-template",
    sections: [
      visitHeader(),
      section("trauma", "Mechanism", [
        area("mechanism", "Mechanism / time / object / safety glasses", true, 3),
        yesno("tetanus-uptodate", "Tetanus up to date?"),
        yesno("chemical", "Chemical exposure?"),
        text("irrigation", "Irrigation (L / time)"),
        select("laterality", "Eye", ["OD", "OS", "OU"], true),
      ]),
      entranceSection(),
      iopSection(),
      anteriorSection(),
      section("integrity", "Globe integrity", [
        odos("seidel", "Seidel"),
        odos("peaked-pupil", "Peaked pupil / iris prolapse"),
        odos("eom-entrapment", "EOM restriction / entrapment"),
        yesno("ct-orbit", "Order orbital CT?"),
      ]),
      posteriorSection(),
      assessmentPlanSection([
        "Corneal abrasion",
        "Corneal FB",
        "Hyphema",
        "Iridodialysis",
        "Open globe — shield, NPO, refer",
        "Orbital fracture suspect",
        "Chemical burn",
      ]),
    ],
  }),
];
