import {
  RELATIONSHIPS,
  SYSTEMIC_HISTORY,
  US_STATES,
  area,
  box,
  checks,
  date,
  display,
  email,
  form,
  heading,
  radio,
  section,
  select,
  sign,
  tel,
  text,
  yesno,
} from "../fields";
import type { PracticeForm } from "../types";

const demographics = [
  heading("Patient"),
  text("last-name", "Last name", true),
  text("first-name", "First name", true),
  text("middle-name", "Middle name"),
  date("dob", "Date of birth", true),
  select("sex", "Sex (insurance)", ["Female", "Male", "Unknown"], true),
  text("preferred-name", "Preferred name"),
  select("pronouns", "Pronouns", ["she/her", "he/him", "they/them", "other", "prefer not to say"]),
  select("marital-status", "Marital status", ["Single", "Married", "Domestic partner", "Divorced", "Widowed", "Other"]),
];

const address = [
  heading("Address"),
  text("street", "Street address", true, { span: 2 }),
  text("unit", "Apt / suite"),
  text("city", "City", true),
  select("state", "State", US_STATES, true),
  text("zip", "ZIP", true),
];

const contact = [
  heading("Contact"),
  tel("mobile", "Mobile phone", true),
  tel("home-phone", "Home phone"),
  email("email", "Email", true),
  select("preferred-contact", "Preferred contact", ["Mobile", "Email", "Home phone", "Portal message"], true),
  yesno("ok-sms", "OK to text appointment reminders?"),
  yesno("ok-voicemail", "OK to leave voicemail with clinical details?"),
];

export const intakeForms: PracticeForm[] = [
  form({
    slug: "new-patient-registration",
    title: "New Patient Registration",
    shortTitle: "Registration",
    category: "intake",
    audience: "patient",
    description:
      "Demographics, contacts, emergency contact, employment, and how the patient found the practice. First page of the Ottehr intake paperwork.",
    ottehrSlot: "intake-paperwork",
    sections: [
      section("patient", "Patient information", [
        ...demographics,
        select("language", "Preferred language", ["English", "Spanish", "Other"], true),
        text("language-other", "If other, specify"),
        select("race", "Race", [
          "American Indian or Alaska Native",
          "Asian",
          "Black or African American",
          "Native Hawaiian or Other Pacific Islander",
          "White",
          "Other",
          "Prefer not to say",
        ]),
        select("ethnicity", "Ethnicity", ["Hispanic or Latino", "Not Hispanic or Latino", "Prefer not to say"]),
      ]),
      section("address", "Home address", address),
      section("contact", "Contact", contact),
      section("emergency", "Emergency contact", [
        text("ec-name", "Name", true),
        select("ec-relationship", "Relationship", RELATIONSHIPS, true),
        tel("ec-phone", "Phone", true),
      ]),
      section("employment", "Employment", [
        text("employer", "Employer"),
        text("occupation", "Occupation / visual demands"),
        yesno("computer-user", "Prolonged near / computer work?"),
        yesno("driver", "Do you drive?"),
        yesno("night-driver", "Do you drive at night?"),
      ]),
      section("referral", "How did you hear about us?", [
        checks("referral-source", "Source", [
          "Insurance directory",
          "Google / web search",
          "Friend or family",
          "Physician referral",
          "Walk-by / neighborhood",
          "Social media",
          "Returning patient",
        ]),
        text("referral-detail", "Referring doctor or name", false, { span: 2 }),
      ]),
    ],
  }),

  form({
    slug: "insurance-assignment",
    title: "Insurance, Assignment of Benefits & Financial Responsibility",
    shortTitle: "Insurance",
    category: "intake",
    audience: "patient",
    description:
      "Vision and medical insurance capture, subscriber details, assignment of benefits, and self-pay acknowledgement for Ottehr payment-option and insurance pages.",
    ottehrSlot: "intake-paperwork",
    sections: [
      section("who", "Patient", [
        text("last-name", "Last name", true),
        text("first-name", "First name", true),
        date("dob", "Date of birth", true),
      ]),
      section("pay", "How will today's visit be paid?", [
        radio(
          "payment-option",
          "Payment option",
          ["Vision insurance", "Medical insurance", "Both vision and medical", "Self-pay"],
          true,
        ),
      ]),
      section("vision", "Vision plan", [
        text("vision-carrier", "Vision carrier (VSP, EyeMed, Spectera, Davis, etc.)"),
        text("vision-member-id", "Member ID"),
        text("vision-group", "Group number"),
        date("vision-effective", "Effective date"),
        yesno("vision-subscriber-is-patient", "Is the patient the subscriber?"),
        text("vision-sub-name", "Subscriber name"),
        date("vision-sub-dob", "Subscriber DOB"),
        select("vision-sub-rel", "Relationship to subscriber", RELATIONSHIPS),
      ]),
      section("medical", "Medical insurance", [
        text("med-carrier", "Medical carrier"),
        text("med-member-id", "Member ID"),
        text("med-group", "Group number"),
        text("med-payer-id", "Payer ID (if known)"),
        yesno("med-subscriber-is-patient", "Is the patient the subscriber?"),
        text("med-sub-name", "Subscriber name"),
        date("med-sub-dob", "Subscriber DOB"),
        select("med-sub-rel", "Relationship to subscriber", RELATIONSHIPS),
        text("med-pcp", "Primary care physician"),
      ]),
      section("secondary", "Secondary / other coverage", [
        yesno("has-secondary", "Secondary medical coverage?"),
        text("sec-carrier", "Secondary carrier"),
        text("sec-member-id", "Member ID"),
      ]),
      section("legal", "Assignment and responsibility", [
        display(
          "aob-text",
          "I authorize this practice to release information required to process insurance claims and I assign payable benefits to the practice. I understand that vision plans typically cover a refraction and materials benefit while medical insurance covers disease-related eye care. I am responsible for copays, deductibles, non-covered services (including refraction when not a plan benefit), and amounts my plan does not pay.",
        ),
        box("aob-agree", "I agree to assignment of benefits and financial responsibility.", true),
        sign("signature"),
        date("sign-date", "Date", true),
      ]),
    ],
  }),

  form({
    slug: "medical-ocular-history",
    title: "Medical & Ocular History Questionnaire",
    shortTitle: "History",
    category: "intake",
    audience: "patient",
    description:
      "Chief complaint, ocular history, systemic history, medications, allergies, family history, and social history. Maps to Ottehr medical history plus optometry-specific ROS.",
    ottehrSlot: "medical-history",
    sections: [
      section("visit", "Today's visit", [
        text("last-name", "Last name", true),
        text("first-name", "First name", true),
        date("dob", "Date of birth", true),
        date("last-eye-exam", "Last eye exam"),
        date("last-dilation", "Last dilated exam"),
        area("chief-complaint", "What is the main reason for today's visit?", true),
        checks("symptoms", "Current symptoms", [
          "Blur at distance",
          "Blur at near",
          "Fluctuating vision",
          "Double vision",
          "Eye pain",
          "Redness",
          "Itching",
          "Burning / gritty",
          "Tearing",
          "Discharge",
          "Light sensitivity",
          "Flashes",
          "Floaters",
          "Curtain / veil",
          "Headache",
          "Eye strain",
          "Dryness",
          "Halos",
          "Night driving difficulty",
          "Loss of vision",
        ]),
      ]),
      section("correction", "Current correction", [
        yesno("wears-glasses", "Do you wear glasses?"),
        select("glasses-use", "Glasses use", ["Full time", "Distance only", "Near only", "Computer / progressives", "Backup only", "None"]),
        yesno("wears-cl", "Do you wear contact lenses?"),
        select("cl-type", "Contact lens type", [
          "None",
          "Daily soft",
          "2-week soft",
          "Monthly soft",
          "Toric",
          "Multifocal",
          "RGP / corneal GP",
          "Scleral",
          "Ortho-K",
          "Hybrid",
        ]),
        text("cl-brand", "Brand / parameters (if known)", false, { span: 2 }),
        text("cl-solution", "Care system"),
        yesno("sleep-in-cls", "Do you ever sleep in contact lenses?"),
      ]),
      section("ocular", "Ocular history", [
        checks("ocular-hx", "Have you been diagnosed with or treated for", [
          "None",
          "Myopia",
          "Hyperopia",
          "Astigmatism",
          "Presbyopia",
          "Amblyopia / lazy eye",
          "Strabismus / eye turn",
          "Cataract",
          "Glaucoma / glaucoma suspect",
          "Macular degeneration",
          "Diabetic retinopathy",
          "Retinal detachment / tear",
          "Keratoconus",
          "Dry eye disease",
          "Uveitis / iritis",
          "Eye injury",
          "Eye surgery",
          "Color vision deficiency",
        ]),
        area("ocular-detail", "Details: surgeries, injuries, year, which eye"),
      ]),
      section("systemic", "Medical history", [
        checks("systemic-hx", "Systemic conditions", SYSTEMIC_HISTORY),
        text("a1c", "Last A1c / blood sugar (if diabetic)"),
        date("diabetes-dx", "Year diagnosed (diabetes)"),
        area("systemic-detail", "Other medical history"),
      ]),
      section("meds", "Medications, allergies, pharmacy", [
        area("medications", "Current medications (include eye drops)", true),
        area("allergies", "Allergies and reactions", true),
        text("pharmacy-name", "Preferred pharmacy", true),
        text("pharmacy-phone", "Pharmacy phone"),
        text("pharmacy-city", "Pharmacy city / cross street"),
      ]),
      section("family", "Family history", [
        checks("family-ocular", "Family eye disease", [
          "None known",
          "Glaucoma",
          "Macular degeneration",
          "Cataract (early)",
          "Retinal detachment",
          "Blindness",
          "Strabismus / amblyopia",
          "Keratoconus",
          "Color blindness",
        ]),
        checks("family-systemic", "Family medical", [
          "None known",
          "Diabetes",
          "Hypertension",
          "Heart disease",
          "Thyroid",
          "Cancer",
          "Autoimmune",
        ]),
      ]),
      section("social", "Social history", [
        select("tobacco", "Tobacco", ["Never", "Former", "Current"], true),
        select("alcohol", "Alcohol", ["None", "Occasional", "Daily", "Prefer not to say"]),
        yesno("pregnant", "Pregnant or nursing?"),
        area("hobbies", "Hobbies, sports, occupational eye hazards"),
      ]),
      section("sign", "Attestation", [
        box("hx-accurate", "I certify this history is complete and accurate to the best of my knowledge.", true),
        sign("signature"),
        date("sign-date", "Date", true),
      ]),
    ],
  }),

  form({
    slug: "hipaa-npp",
    title: "HIPAA Notice of Privacy Practices Acknowledgement",
    shortTitle: "HIPAA",
    category: "consent",
    audience: "patient",
    description:
      "Acknowledgement that the patient received the Notice of Privacy Practices. Drop-in for Ottehr consent-forms hipaa-acknowledgement.",
    ottehrSlot: "consent-forms",
    sections: [
      section("notice", "Notice of Privacy Practices", [
        display(
          "npp-body",
          "This practice uses and discloses protected health information for treatment, payment, and health-care operations as described in our Notice of Privacy Practices. You may request a paper copy at any time, restrict certain disclosures, request confidential communications, inspect or amend your record, and file a complaint without retaliation. We may share information with other treating providers, your insurance plan, and people you designate below.",
        ),
        text("last-name", "Last name", true),
        text("first-name", "First name", true),
        date("dob", "Date of birth", true),
        box("received-npp", "I acknowledge I have received or been offered a copy of the Notice of Privacy Practices.", true),
        area("authorized-contacts", "People we may discuss my care with (name and relationship)"),
        yesno("leave-detailed-message", "May we leave detailed clinical messages at the numbers on file?"),
        sign("signature"),
        select("signer-relationship", "Relationship to patient", RELATIONSHIPS, true),
        date("sign-date", "Date", true),
      ]),
    ],
  }),

  form({
    slug: "consent-to-treat",
    title: "Consent to Examine, Treat & Guarantee of Payment",
    shortTitle: "Consent to treat",
    category: "consent",
    audience: "patient",
    description:
      "General consent for optometric examination, diagnostic drops, and treatment, plus guarantee of payment. Maps to Ottehr consent-to-treat.",
    ottehrSlot: "consent-forms",
    sections: [
      section("consent", "Consent", [
        text("last-name", "Last name", true),
        text("first-name", "First name", true),
        date("dob", "Date of birth", true),
        display(
          "ctt-body",
          "I consent to optometric examination and treatment by the doctors and staff of this practice. This may include refraction, binocular testing, intraocular pressure, slit-lamp examination, dilated fundus examination, retinal imaging, anterior and posterior OCT, visual fields, corneal topography, and other tests the doctor considers medically appropriate. Diagnostic drops may cause temporary light sensitivity and blurred vision. I may refuse any test. I am responsible for charges my plan does not cover, including refraction (CPT 92015) when it is a non-covered service, and I authorize a card on file to be charged for patient-responsibility balances after insurance adjudication.",
        ),
        box("consent-treat", "I consent to examination and treatment.", true),
        box("consent-payment", "I guarantee payment of amounts I owe.", true),
        sign("signature"),
        select("signer-relationship", "Relationship to patient", RELATIONSHIPS, true),
        date("sign-date", "Date", true),
      ]),
    ],
  }),

  form({
    slug: "financial-policy",
    title: "Financial, Cancellation & Materials Policy",
    shortTitle: "Financial policy",
    category: "admin",
    audience: "patient",
    description: "Copays at check-in, non-covered services, no-show fees, glasses/contact lens order deposits, and returns.",
    ottehrSlot: "consent-forms",
    sections: [
      section("policy", "Practice financial policy", [
        text("last-name", "Last name", true),
        text("first-name", "First name", true),
        display(
          "fin-body",
          "Copays and known self-pay amounts are due at check-in. We bill vision plans for routine exams and materials when eligible, and medical insurance for disease-related visits. Refraction, contact lens evaluation, retinal screening images, and premium testing may be patient-pay if not a covered benefit. Glasses and contact lens orders require a deposit. Custom products are non-refundable once ordered. Missed appointments or cancellations inside 24 hours may incur a fee. Returned checks and declined cards may incur a processing fee.",
        ),
        text("no-show-fee", "No-show / late-cancel fee", false, { defaultValue: "$50" }),
        text("cl-eval-fee", "Contact lens evaluation starting fee", false, {
          defaultValue: "See fee schedule",
        }),
        box("agree-financial", "I have read and agree to this financial policy.", true),
        sign("signature"),
        date("sign-date", "Date", true),
      ]),
    ],
  }),

  form({
    slug: "communication-authorization",
    title: "Communication & Patient Portal Authorization",
    shortTitle: "Communications",
    category: "intake",
    audience: "patient",
    description: "SMS, email, portal, and telehealth contact preferences for Ottehr messaging.",
    ottehrSlot: "intake-paperwork",
    sections: [
      section("comm", "How we may contact you", [
        text("last-name", "Last name", true),
        text("first-name", "First name", true),
        email("email", "Email", true),
        tel("mobile", "Mobile", true),
        checks("channels", "Approved channels", [
          "SMS appointment reminders",
          "SMS recall / glasses ready",
          "Email recall",
          "Patient portal",
          "Telephone",
        ]),
        yesno("ok-clinical-sms", "OK to send non-sensitive clinical follow-up by SMS?"),
        box("portal-agree", "I agree to use the patient portal for messages when possible."),
        sign("signature"),
        date("sign-date", "Date", true),
      ]),
    ],
  }),

  form({
    slug: "release-of-records",
    title: "Authorization to Release / Obtain Records",
    shortTitle: "Records release",
    category: "admin",
    audience: "patient",
    description: "Two-way records authorization for prior OD/OMD, PCP, and imaging centers.",
    ottehrSlot: "forms-list",
    sections: [
      section("who", "Patient", [
        text("last-name", "Last name", true),
        text("first-name", "First name", true),
        date("dob", "Date of birth", true),
      ]),
      section("direction", "Authorization", [
        radio("direction", "I authorize this practice to", ["Release my records to", "Obtain my records from", "Both"], true),
        text("other-practice", "Name of provider / practice", true, { span: 2 }),
        text("other-phone", "Phone"),
        text("other-fax", "Fax"),
        area("other-address", "Address"),
        checks("what", "Records to include", [
          "Complete eye record",
          "Last exam only",
          "Prescriptions",
          "Imaging / OCT / photos",
          "Visual fields",
          "Lab / letters",
        ]),
        date("valid-until", "Valid until (blank = one year)"),
        box("redisclose", "I understand information may be re-disclosed by the recipient and no longer protected by HIPAA if they are not a covered entity."),
        sign("signature"),
        date("sign-date", "Date", true),
      ]),
    ],
  }),

  form({
    slug: "pediatric-guardian",
    title: "Pediatric / Minor Consent & Guardian Authorization",
    shortTitle: "Minor consent",
    category: "consent",
    audience: "patient",
    description: "Required when the patient is under 18. Authorizes exam, dilation, and who may accompany the child.",
    ottehrSlot: "consent-forms",
    sections: [
      section("child", "Minor patient", [
        text("child-last", "Child last name", true),
        text("child-first", "Child first name", true),
        date("child-dob", "Date of birth", true),
        text("school", "School / grade"),
      ]),
      section("guardian", "Parent or legal guardian", [
        text("guardian-name", "Guardian name", true),
        select("guardian-rel", "Relationship", ["Parent", "Legal Guardian", "Foster parent", "Other"], true),
        tel("guardian-phone", "Phone", true),
        area("other-adults", "Other adults authorized to accompany this child and consent to routine care"),
        box("consent-minor", "I consent to examination, diagnostic drops including dilation, and treatment for this minor.", true),
        box("polycarb", "I understand polycarbonate or Trivex lenses are strongly recommended for children and monocular patients."),
        sign("signature"),
        date("sign-date", "Date", true),
      ]),
    ],
  }),

  form({
    slug: "photo-consent",
    title: "Photography, Imaging & Education Consent",
    shortTitle: "Photo consent",
    category: "consent",
    audience: "patient",
    description: "Clinical photography vs optional marketing/education use of de-identified images.",
    ottehrSlot: "consent-forms",
    sections: [
      section("photo", "Images", [
        text("last-name", "Last name", true),
        text("first-name", "First name", true),
        box("clinical-images", "I consent to clinical photographs and retinal images for my medical record.", true),
        yesno("teaching", "May de-identified images be used for staff teaching?"),
        yesno("marketing", "May de-identified images be used in practice education materials? (optional)"),
        sign("signature"),
        date("sign-date", "Date", true),
      ]),
    ],
  }),

  form({
    slug: "preferred-pharmacy",
    title: "Preferred Pharmacy & eRx",
    shortTitle: "Pharmacy",
    category: "intake",
    audience: "patient",
    description: "Pharmacy of record for Ottehr eRx routing.",
    ottehrSlot: "intake-paperwork",
    sections: [
      section("rx", "Pharmacy", [
        text("last-name", "Last name", true),
        text("first-name", "First name", true),
        text("pharmacy-name", "Pharmacy name", true),
        text("pharmacy-address", "Address / cross streets", true, { span: 2 }),
        tel("pharmacy-phone", "Phone"),
        text("pharmacy-ncpdp", "NCPDP / NPI if known"),
        yesno("mail-order", "Also use a mail-order pharmacy?"),
        text("mail-order-name", "Mail-order name"),
        sign("signature"),
        date("sign-date", "Date", true),
      ]),
    ],
  }),

  form({
    slug: "telehealth-consent",
    title: "Telehealth Consent",
    shortTitle: "Telehealth",
    category: "consent",
    audience: "patient",
    description: "Consent for Ottehr virtual visits: limits of remote eye care, emergency instructions, and privacy.",
    ottehrSlot: "consent-forms",
    sections: [
      section("tele", "Telehealth", [
        text("last-name", "Last name", true),
        text("first-name", "First name", true),
        display(
          "tele-body",
          "A telehealth visit cannot replace a comprehensive in-person dilated examination. Remote care is limited by camera quality, lighting, and the inability to measure pressure or view the far retinal periphery. If I have flashes, floaters with a curtain, sudden vision loss, chemical injury, or severe pain I will seek emergency in-person care. I understand state licensure rules: the doctor must be licensed where I am physically located during the visit.",
        ),
        box("tele-agree", "I consent to telehealth as described.", true),
        sign("signature"),
        date("sign-date", "Date", true),
      ]),
    ],
  }),
];
