/**
 * Drop-in medical-history quick picks for packages/utils/lib/ottehr-config/medical-history
 */
export const MEDICAL_HISTORY_CONFIG = Object.freeze({
  medicalConditions: {
    quickPicks: [
      { display: "Type 2 diabetes", code: "E11.9" },
      { display: "Type 1 diabetes", code: "E10.9" },
      { display: "Hypertension", code: "I10" },
      { display: "Hyperlipidemia", code: "E78.5" },
      { display: "Thyroid disease", code: "E03.9" },
      { display: "Rheumatoid arthritis", code: "M06.9" },
      { display: "Sjogren syndrome", code: "M35.00" },
      { display: "SLE", code: "M32.9" },
      { display: "Multiple sclerosis", code: "G35" },
      { display: "Migraine", code: "G43.909" },
      { display: "Asthma", code: "J45.909" },
      { display: "Sleep apnea", code: "G47.33" },
      { display: "Myopia", code: "H52.13" },
      { display: "Hyperopia", code: "H52.03" },
      { display: "Astigmatism", code: "H52.223" },
      { display: "Presbyopia", code: "H52.4" },
      { display: "Dry eye", code: "H04.123" },
      { display: "Cataract", code: "H25.13" },
      { display: "Glaucoma suspect", code: "H40.013" },
      { display: "POAG", code: "H40.11X0" },
      { display: "AMD", code: "H35.3130" },
      { display: "Keratoconus", code: "H18.613" },
      { display: "Amblyopia", code: "H53.003" },
      { display: "Strabismus", code: "H50.00" },
    ],
  },
  allergies: {
    quickPicks: [
      { name: "Fluorescein", id: 90001 },
      { name: "Proparacaine / tetracaine", id: 90002 },
      { name: "Tropicamide", id: 90003 },
      { name: "Phenylephrine", id: 90004 },
      { name: "Cyclopentolate", id: 90005 },
      { name: "Preservative (BAK)", id: 90006 },
      { name: "Penicillin", id: 138 },
      { name: "Sulfa", id: 293 },
      { name: "Aspirin", id: 229 },
      { name: "Latex", id: 90007 },
    ],
  },
  medications: {
    quickPicks: [
      { name: "Latanoprost", strength: "0.005%", id: 91001 },
      { name: "Timolol", strength: "0.5%", id: 91002 },
      { name: "Dorzolamide/timolol", strength: "22.3-6.8 mg/mL", id: 91003 },
      { name: "Brimonidine", strength: "0.2%", id: 91004 },
      { name: "Prednisolone acetate", strength: "1%", id: 91005 },
      { name: "Ketorolac", strength: "0.5%", id: 91006 },
      { name: "Ofloxacin", strength: "0.3%", id: 91007 },
      { name: "Erythromycin ointment", strength: "0.5%", id: 91008 },
      { name: "Cyclosporine", strength: "0.05%", id: 91009 },
      { name: "Lifitegrast", strength: "5%", id: 91010 },
      { name: "Artificial tears PF", strength: "1 drop", id: 91011 },
      { name: "Atropine", strength: "0.01%", id: 91012 },
    ],
  },
  inHouseMedications: {
    quickPicks: [
      {
        name: "Tropicamide",
        dose: 1,
        units: "%",
        route: "ophthalmic",
        instructions: "1 drop OD/OS/OU for dilation.",
      },
      {
        name: "Phenylephrine",
        dose: 2.5,
        units: "%",
        route: "ophthalmic",
        instructions: "1 drop for dilation when indicated.",
      },
      {
        name: "Fluorescein strip",
        dose: 1,
        units: "strip",
        route: "ophthalmic",
        instructions: "Moisten and apply to inferior fornix.",
      },
      {
        name: "Proparacaine",
        dose: 0.5,
        units: "%",
        route: "ophthalmic",
        instructions: "1 drop for tonometry or FB removal.",
      },
    ],
  },
});
