// Curated, hand-authored concept questions. These carry clinical nuance and
// power the free-sample set and the tutored-mode explanations.

export interface Fact {
  part: "PART_1" | "PART_2" | "PART_3";
  subject: string;
  topic?: string;
  q: string;
  a: string;
  d: string[];
  e: string;
  ref: string;
  diff?: "EASY" | "MEDIUM" | "HARD";
  free?: boolean;
}

export const CONCEPT_FACTS: Fact[] = [
  // ---------------- PART 1 ----------------
  {
    part: "PART_1",
    subject: "ocular-anatomy-physiology",
    topic: "cornea-and-tear-film",
    q: "Which corneal layer is primarily responsible for maintaining stromal deturgescence (relative dehydration)?",
    a: "Endothelium",
    d: ["Epithelium", "Bowman's layer", "Descemet's membrane"],
    e: "The corneal endothelium contains Na⁺/K⁺-ATPase pumps that actively move fluid out of the stroma, maintaining deturgescence and corneal clarity. Endothelial cell loss (e.g., Fuchs' dystrophy) leads to stromal edema.",
    ref: "Ocular anatomy: corneal endothelium",
    diff: "MEDIUM",
    free: true,
  },
  {
    part: "PART_1",
    subject: "ocular-anatomy-physiology",
    topic: "retina-and-photoreceptors",
    q: "Which photoreceptor type is responsible for high-acuity photopic (daylight) and color vision?",
    a: "Cones",
    d: ["Rods", "Horizontal cells", "Amacrine cells"],
    e: "Cones mediate photopic vision, high spatial acuity (densest at the fovea), and color discrimination. Rods mediate scotopic vision and are absent at the foveola.",
    ref: "Ocular physiology: photoreceptors",
    diff: "EASY",
    free: true,
  },
  {
    part: "PART_1",
    subject: "ocular-anatomy-physiology",
    topic: "uvea-and-aqueous-dynamics",
    q: "Aqueous humor is primarily produced by which structure?",
    a: "Ciliary body (non-pigmented epithelium)",
    d: ["Trabecular meshwork", "Lacrimal gland", "Corneal endothelium"],
    e: "The non-pigmented epithelium of the ciliary processes secretes aqueous humor, largely via active transport by carbonic anhydrase. It drains through the trabecular meshwork (conventional) and uveoscleral pathways.",
    ref: "Ocular physiology: aqueous dynamics",
    diff: "EASY",
  },
  {
    part: "PART_1",
    subject: "ocular-anatomy-physiology",
    topic: "visual-pathway-and-cortex",
    q: "A lesion at the optic chiasm classically produces which visual field defect?",
    a: "Bitemporal hemianopia",
    d: ["Binasal hemianopia", "Homonymous hemianopia", "Central scotoma"],
    e: "Crossing nasal retinal fibers (temporal visual fields) are affected at the chiasm, producing bitemporal hemianopia. A pituitary adenoma is a classic cause.",
    ref: "Neuroanatomy: chiasmal lesions",
    diff: "MEDIUM",
    free: true,
  },
  {
    part: "PART_1",
    subject: "geometric-physical-optics",
    topic: "polarization",
    q: "Polarized sunglasses reduce glare primarily by blocking light that is polarized in which orientation?",
    a: "Horizontally",
    d: ["Vertically", "Circularly only", "At 45° only"],
    e: "Light reflected off horizontal surfaces (water, roads) becomes horizontally polarized. Polarized lenses have a vertical transmission axis, blocking the horizontal glare component.",
    ref: "Physical optics: polarization",
    diff: "EASY",
  },
  {
    part: "PART_1",
    subject: "ocular-systemic-pharmacology",
    topic: "glaucoma-medications",
    q: "Which class of glaucoma medication lowers IOP mainly by increasing uveoscleral outflow?",
    a: "Prostaglandin analogs",
    d: ["Beta-blockers", "Carbonic anhydrase inhibitors", "Alpha-2 agonists"],
    e: "Prostaglandin analogs (e.g., latanoprost) increase uveoscleral outflow and are first-line for POAG. Beta-blockers and CAIs reduce aqueous production; alpha-2 agonists do both.",
    ref: "Pharmacology: glaucoma therapeutics",
    diff: "MEDIUM",
    free: true,
  },
  {
    part: "PART_1",
    subject: "ocular-systemic-pharmacology",
    topic: "mydriatics-and-cycloplegics",
    q: "Which agent provides the strongest and longest-lasting cycloplegia, useful in young hyperopes?",
    a: "Atropine",
    d: ["Tropicamide", "Phenylephrine", "Cyclopentolate 0.5%"],
    e: "Atropine is the most potent, longest-acting cycloplegic (effects for days to two weeks). Tropicamide is short-acting; phenylephrine is a sympathomimetic mydriatic with no cycloplegia.",
    ref: "Pharmacology: cycloplegics",
    diff: "MEDIUM",
  },
  {
    part: "PART_1",
    subject: "ocular-systemic-pharmacology",
    topic: "autonomic-pharmacology",
    q: "Pilocarpine causes miosis by acting as a(n):",
    a: "Direct muscarinic agonist",
    d: ["Muscarinic antagonist", "Alpha-1 agonist", "Beta antagonist"],
    e: "Pilocarpine directly stimulates muscarinic receptors on the iris sphincter, producing miosis, and on the ciliary muscle, producing accommodation and opening the trabecular meshwork.",
    ref: "Autonomic pharmacology: cholinergics",
    diff: "MEDIUM",
  },
  {
    part: "PART_1",
    subject: "biochemistry-molecular-biology",
    topic: "phototransduction-cascade",
    q: "In phototransduction, activated rhodopsin triggers a G-protein that reduces the level of which second messenger?",
    a: "cGMP",
    d: ["cAMP", "IP3", "Calcium via ryanodine"],
    e: "Light activates rhodopsin → transducin → phosphodiesterase, which hydrolyzes cGMP. Falling cGMP closes cation channels, hyperpolarizing the photoreceptor.",
    ref: "Biochemistry: phototransduction",
    diff: "HARD",
  },
  {
    part: "PART_1",
    subject: "microbiology-immunology",
    topic: "bacteriology",
    q: "Which organism is capable of penetrating an intact corneal epithelium?",
    a: "Neisseria gonorrhoeae",
    d: ["Staphylococcus aureus", "Streptococcus pneumoniae", "Pseudomonas aeruginosa"],
    e: "Neisseria gonorrhoeae, along with Corynebacterium diphtheriae, Haemophilus, and Listeria, can penetrate intact corneal epithelium — making hyperacute conjunctivitis an emergency.",
    ref: "Ocular microbiology",
    diff: "HARD",
    free: true,
  },
  {
    part: "PART_1",
    subject: "general-ocular-pathology",
    topic: "acute-and-chronic-inflammation",
    q: "Which cell type predominates in acute inflammation?",
    a: "Neutrophils",
    d: ["Lymphocytes", "Plasma cells", "Eosinophils"],
    e: "Neutrophils are the first responders in acute inflammation. Lymphocytes and plasma cells predominate in chronic inflammation; eosinophils in allergic/parasitic processes.",
    ref: "Pathology: inflammation",
    diff: "EASY",
  },
  {
    part: "PART_1",
    subject: "genetics",
    topic: "inheritance-patterns",
    q: "Leber hereditary optic neuropathy (LHON) follows which inheritance pattern?",
    a: "Mitochondrial (maternal)",
    d: ["Autosomal dominant", "X-linked recessive", "Autosomal recessive"],
    e: "LHON is caused by mitochondrial DNA mutations and is inherited maternally; affected males cannot transmit it. It causes bilateral, sequential painless central vision loss in young men.",
    ref: "Genetics: mitochondrial inheritance",
    diff: "MEDIUM",
  },
  {
    part: "PART_1",
    subject: "neuroscience-of-vision",
    topic: "color-vision-processing",
    q: "The opponent-process theory of color vision is best supported at which level?",
    a: "Retinal ganglion cells and LGN",
    d: ["Photoreceptor outer segments", "Corneal nerves", "Ciliary ganglion"],
    e: "Opponent processing (red-green, blue-yellow, black-white) emerges in ganglion cells and the lateral geniculate nucleus, while trichromatic theory describes cone-level absorption.",
    ref: "Visual neuroscience: color",
    diff: "HARD",
  },
  {
    part: "PART_1",
    subject: "biostatistics-epidemiology",
    topic: "study-design",
    q: "Which study design is best for establishing incidence and temporal (cause-then-effect) relationships?",
    a: "Prospective cohort study",
    d: ["Case-control study", "Cross-sectional study", "Case series"],
    e: "Prospective cohort studies follow exposed and unexposed groups forward in time, allowing calculation of incidence and relative risk with clear temporality. Case-control studies are efficient for rare diseases but yield odds ratios.",
    ref: "Epidemiology: study design",
    diff: "MEDIUM",
  },

  // ---------------- PART 2 ----------------
  {
    part: "PART_2",
    subject: "glaucoma",
    topic: "primary-open-angle-glaucoma",
    q: "Which is the strongest modifiable risk factor for primary open-angle glaucoma progression?",
    a: "Elevated intraocular pressure",
    d: ["Myopia", "Family history", "Age"],
    e: "IOP is the only major modifiable risk factor and the target of all current therapy. Age, family history, and race are non-modifiable risk factors.",
    ref: "Glaucoma: risk factors",
    diff: "EASY",
    free: true,
  },
  {
    part: "PART_2",
    subject: "glaucoma",
    topic: "angle-closure-glaucoma",
    q: "The definitive treatment to prevent recurrence of acute primary angle closure is:",
    a: "Laser peripheral iridotomy",
    d: ["Topical timolol", "Oral acetazolamide", "Trabeculectomy"],
    e: "Laser peripheral iridotomy relieves pupillary block, the mechanism of acute angle closure. Medications lower IOP acutely but do not address the anatomic cause.",
    ref: "Glaucoma: angle closure management",
    diff: "MEDIUM",
    free: true,
  },
  {
    part: "PART_2",
    subject: "posterior-segment-disease",
    topic: "diabetic-retinopathy",
    q: "Which finding defines proliferative diabetic retinopathy?",
    a: "Neovascularization",
    d: ["Microaneurysms", "Hard exudates", "Dot-blot hemorrhages"],
    e: "Neovascularization of the disc or elsewhere defines PDR and warrants prompt treatment (anti-VEGF or PRP). Microaneurysms, exudates, and dot-blot hemorrhages are non-proliferative signs.",
    ref: "Retina: diabetic retinopathy staging",
    diff: "EASY",
    free: true,
  },
  {
    part: "PART_2",
    subject: "posterior-segment-disease",
    topic: "age-related-macular-degeneration",
    q: "The hallmark early clinical sign of age-related macular degeneration is:",
    a: "Drusen",
    d: ["Cotton-wool spots", "Roth spots", "Lisch nodules"],
    e: "Drusen (sub-RPE deposits) are the hallmark of early/intermediate AMD. Large, soft, confluent drusen increase the risk of progression to advanced AMD.",
    ref: "Retina: AMD",
    diff: "EASY",
  },
  {
    part: "PART_2",
    subject: "posterior-segment-disease",
    topic: "retinal-vascular-occlusions",
    q: "A patient with sudden painless vision loss shows a cherry-red spot at the macula. The most likely diagnosis is:",
    a: "Central retinal artery occlusion",
    d: ["Central retinal vein occlusion", "Wet AMD", "Optic neuritis"],
    e: "A cherry-red spot results from a pale, edematous retina with the intact choroidal circulation visible through the thin fovea — classic for CRAO, an ocular emergency.",
    ref: "Retina: CRAO",
    diff: "MEDIUM",
    free: true,
  },
  {
    part: "PART_2",
    subject: "anterior-segment-disease",
    topic: "keratitis-and-corneal-ulcers",
    q: "A contact lens wearer presents with a painful corneal ulcer with a soupy, greenish infiltrate. The most likely organism is:",
    a: "Pseudomonas aeruginosa",
    d: ["Herpes simplex virus", "Acanthamoeba", "Staphylococcus epidermidis"],
    e: "Pseudomonas is the most common cause of contact-lens-related bacterial keratitis, producing a rapidly progressive ulcer with a mucopurulent (often greenish) discharge. It requires aggressive fluoroquinolone therapy.",
    ref: "Cornea: microbial keratitis",
    diff: "MEDIUM",
    free: true,
  },
  {
    part: "PART_2",
    subject: "anterior-segment-disease",
    topic: "dry-eye-disease",
    q: "Which test specifically evaluates aqueous tear production?",
    a: "Schirmer test",
    d: ["Tear break-up time", "Meibography", "Corneal topography"],
    e: "The Schirmer test measures aqueous tear volume. Tear break-up time evaluates tear film stability (often evaporative/MGD-related), and meibography images the meibomian glands.",
    ref: "Cornea: dry eye assessment",
    diff: "EASY",
  },
  {
    part: "PART_2",
    subject: "neuro-optometry",
    topic: "pupillary-abnormalities",
    q: "A relative afferent pupillary defect (RAPD) indicates a lesion of the:",
    a: "Afferent visual pathway (optic nerve or extensive retina)",
    d: ["Iris sphincter muscle", "Third cranial nerve", "Sympathetic chain"],
    e: "An RAPD reflects asymmetric afferent input, typically from optic neuropathy (e.g., optic neuritis) or extensive retinal disease. Efferent lesions (CN III, sympathetics) affect pupil size, not the afferent response.",
    ref: "Neuro-optometry: RAPD",
    diff: "MEDIUM",
    free: true,
  },
  {
    part: "PART_2",
    subject: "neuro-optometry",
    topic: "cranial-nerve-palsies",
    q: "A patient has ptosis, a 'down and out' eye, and a dilated pupil. Which cranial nerve is affected, and why is the dilated pupil concerning?",
    a: "CN III — pupil involvement suggests a compressive lesion (e.g., aneurysm)",
    d: ["CN IV — pupil-sparing microvascular", "CN VI — benign", "CN VII — Bell's palsy"],
    e: "A pupil-involving third-nerve palsy is a red flag for compression, classically a posterior communicating artery aneurysm, because parasympathetic fibers run superficially and are affected early. This needs urgent neuroimaging.",
    ref: "Neuro-optometry: CN III palsy",
    diff: "HARD",
    free: true,
  },
  {
    part: "PART_2",
    subject: "systemic-disease",
    topic: "thyroid-eye-disease",
    q: "The most common cause of unilateral AND bilateral proptosis in adults is:",
    a: "Thyroid eye disease",
    d: ["Orbital cellulitis", "Orbital lymphoma", "Cavernous hemangioma"],
    e: "Thyroid (Graves') eye disease is the most common cause of both unilateral and bilateral proptosis in adults. The inferior and medial recti are most often enlarged (tendon-sparing).",
    ref: "Systemic disease: thyroid orbitopathy",
    diff: "MEDIUM",
  },
  {
    part: "PART_2",
    subject: "binocular-vision-pediatrics",
    topic: "amblyopia",
    q: "The most effective first-line treatment for moderate anisometropic amblyopia in a 5-year-old after refractive correction is:",
    a: "Patching of the sound eye",
    d: ["Vision therapy only", "Surgery", "Observation"],
    e: "After a period of optical correction (refractive adaptation), patching (occlusion) of the better-seeing eye is first-line. Atropine penalization is an effective alternative for moderate amblyopia.",
    ref: "Pediatrics: amblyopia therapy",
    diff: "MEDIUM",
  },
  {
    part: "PART_2",
    subject: "binocular-vision-pediatrics",
    topic: "vergence-dysfunction",
    q: "A patient reports near asthenopia and diplopia; testing shows reduced positive fusional vergence and exophoria greater at near. The diagnosis is:",
    a: "Convergence insufficiency",
    d: ["Convergence excess", "Divergence insufficiency", "Basic esophoria"],
    e: "Convergence insufficiency features exophoria greater at near, a receded near point of convergence, and reduced positive fusional vergence. First-line management is vergence/accommodative therapy.",
    ref: "Binocular vision: convergence insufficiency",
    diff: "MEDIUM",
    free: true,
  },
  {
    part: "PART_2",
    subject: "contact-lenses",
    topic: "rigid-gas-permeable-fitting",
    q: "With fluorescein evaluation of an RGP lens, central pooling (bright fluorescence) indicates a fit that is:",
    a: "Too steep (apical clearance)",
    d: ["Too flat (apical bearing)", "Optimal alignment", "Decentered temporally"],
    e: "Central pooling means tears collect under the lens center — the base curve is steeper than the cornea (apical clearance). A flat fit shows central touch (dark) with peripheral pooling.",
    ref: "Contact lenses: RGP fluorescein patterns",
    diff: "MEDIUM",
  },
  {
    part: "PART_2",
    subject: "ocular-therapeutics",
    topic: "anti-inflammatory-therapy",
    q: "Before prescribing a topical corticosteroid for a red eye, it is most important to rule out:",
    a: "Herpes simplex epithelial (dendritic) keratitis",
    d: ["Allergic conjunctivitis", "Dry eye", "Pinguecula"],
    e: "Steroids dramatically worsen active HSV epithelial keratitis and can cause geographic ulcers. Always rule out dendritic keratitis (fluorescein staining) before steroid use, and monitor IOP.",
    ref: "Therapeutics: steroid safety",
    diff: "MEDIUM",
    free: true,
  },
  {
    part: "PART_2",
    subject: "low-vision",
    topic: "low-vision-assessment",
    q: "The Kestenbaum rule estimates the near add (in diopters) needed for 1M print as:",
    a: "The reciprocal of the best-corrected distance acuity (as a fraction)",
    d: ["Distance acuity denominator ÷ 10", "Always +2.50 D", "Half the amplitude of accommodation"],
    e: "Kestenbaum's rule: the starting add equals the reciprocal of the distance acuity expressed as a fraction (e.g., 20/100 → add ≈ +5.00 D). It provides a starting point that is refined by trial.",
    ref: "Low vision: Kestenbaum rule",
    diff: "HARD",
  },
  {
    part: "PART_2",
    subject: "public-health-practice",
    topic: "ethics-and-informed-consent",
    q: "The ethical principle that obligates a clinician to act in the patient's best interest is:",
    a: "Beneficence",
    d: ["Autonomy", "Justice", "Non-maleficence"],
    e: "Beneficence is the duty to act for the patient's benefit. Non-maleficence is 'do no harm', autonomy respects patient choice, and justice concerns fair distribution of care.",
    ref: "Ethics: core principles",
    diff: "EASY",
  },

  // ---------------- PART 3 ----------------
  {
    part: "PART_3",
    subject: "glaucoma-iop-skills",
    topic: "goldmann-applanation-tonometry",
    q: "During Goldmann applanation tonometry, the endpoint is reached when the inner edges of the two fluorescein semicircles (mires):",
    a: "Just touch / overlap slightly, pulsating",
    d: ["Are widely separated", "Form one large ring", "Disappear completely"],
    e: "The correct endpoint is when the inner borders of the mires just touch (or the pulsation midpoint aligns). Thick mires indicate excess fluorescein; thin mires indicate too little.",
    ref: "Clinical skills: Goldmann tonometry",
    diff: "MEDIUM",
    free: true,
  },
  {
    part: "PART_3",
    subject: "glaucoma-iop-skills",
    topic: "gonioscopy",
    q: "Using the Shaffer grading system in gonioscopy, a Grade 0 angle indicates:",
    a: "Closed angle (no structures visible)",
    d: ["Wide open 45° angle", "Ciliary body visible", "Scleral spur visible"],
    e: "In the Shaffer system, Grade 4 is widest (≈45°, ciliary body band visible) and Grade 0 is a closed angle with iridocorneal contact and no angle structures visible.",
    ref: "Clinical skills: gonioscopy grading",
    diff: "MEDIUM",
  },
  {
    part: "PART_3",
    subject: "refractive-skills",
    topic: "static-retinoscopy",
    q: "During 'with' motion in retinoscopy at a 66 cm working distance, you should:",
    a: "Add plus power until neutrality, then subtract the working distance lens (+1.50 D)",
    d: ["Add minus power until neutrality", "Stop immediately at with motion", "Ignore working distance"],
    e: "'With' motion is neutralized by adding plus. After reaching neutrality you subtract the working-distance dioptric value (1 / 0.66 m ≈ +1.50 D) to obtain the refractive error.",
    ref: "Clinical skills: retinoscopy",
    diff: "MEDIUM",
    free: true,
  },
  {
    part: "PART_3",
    subject: "refractive-skills",
    topic: "subjective-refraction",
    q: "The Jackson cross cylinder is used to refine:",
    a: "Cylinder axis and power",
    d: ["Sphere only", "Vertex distance", "Pupillary distance"],
    e: "The JCC refines astigmatic correction: first axis (flipping with the axis aligned to the JCC handle) then power. Sphere is balanced separately to maintain the spherical equivalent.",
    ref: "Clinical skills: JCC refinement",
    diff: "MEDIUM",
  },
  {
    part: "PART_3",
    subject: "sensorimotor-neuro-skills",
    topic: "pupillary-testing-and-apd",
    q: "The swinging flashlight test is used to detect a(n):",
    a: "Relative afferent pupillary defect",
    d: ["Accommodative spasm", "Cataract", "Refractive error"],
    e: "The swinging flashlight test alternates illumination between eyes; paradoxical dilation of an eye when the light swings to it indicates an RAPD (afferent pathway defect).",
    ref: "Clinical skills: swinging flashlight",
    diff: "EASY",
    free: true,
  },
  {
    part: "PART_3",
    subject: "sensorimotor-neuro-skills",
    topic: "cover-test",
    q: "In the cover test, an inward refixation movement of the uncovered eye when the other eye is covered indicates:",
    a: "Exodeviation",
    d: ["Esodeviation", "Hyperdeviation", "Orthophoria"],
    e: "If the eye moves inward (nasally) to pick up fixation, it was previously turned out — an exodeviation. An outward refixation movement indicates an esodeviation.",
    ref: "Clinical skills: cover test",
    diff: "MEDIUM",
    free: true,
  },
  {
    part: "PART_3",
    subject: "anterior-segment-skills",
    topic: "van-herick-angle-estimation",
    q: "In the Van Herick technique, a peripheral anterior chamber depth that is 1/4 of the corneal section thickness corresponds to:",
    a: "Grade 2 (angle capable of closure)",
    d: ["Grade 4 (wide open)", "Grade 0 (closed)", "Grade 3 (open)"],
    e: "Van Herick grading: ACD ≥ full corneal thickness = Grade 4; = 1/2 corneal thickness = Grade 3; = 1/4 = Grade 2 (narrow, closure possible); < 1/4 = Grade 1 (closure likely).",
    ref: "Clinical skills: Van Herick",
    diff: "MEDIUM",
  },
  {
    part: "PART_3",
    subject: "posterior-segment-skills",
    topic: "binocular-indirect-ophthalmoscopy",
    q: "The image observed with binocular indirect ophthalmoscopy is:",
    a: "Real, inverted, and reversed",
    d: ["Virtual and erect", "Real and erect", "Virtual and inverted"],
    e: "BIO forms a real, aerial image that is inverted top-to-bottom and reversed left-to-right, which is why examiners mentally flip the drawing when charting fundus findings.",
    ref: "Clinical skills: BIO optics",
    diff: "MEDIUM",
    free: true,
  },
  {
    part: "PART_3",
    subject: "anterior-segment-skills",
    topic: "slit-lamp-biomicroscopy",
    q: "Which slit-lamp illumination technique is best for viewing corneal endothelial cells and subtle edema?",
    a: "Specular reflection",
    d: ["Diffuse illumination", "Sclerotic scatter", "Direct focal (broad beam)"],
    e: "Specular reflection aligns the angle of incidence and reflection to reveal the endothelial mosaic and subtle surface changes. Sclerotic scatter highlights central corneal opacities via total internal reflection.",
    ref: "Clinical skills: slit-lamp illumination",
    diff: "HARD",
  },
];
